config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('signup/', views.signup, name="signup"),
    path('item/', views.item, name="add_item"),
    path('item-view/', views.item_view, name="item_view"),
    path('item-view/<int:pk>/', views.PostDisplay.as_view(), name="item_details"),
    path('item-view/<int:pk>/like', views.AddLike.as_view(), name="like"),
    path('item-view/<int:pk>/dislike', views.AddDislike.as_view(), name="dislike"),
    path('item-view/<int:pk>/delete', views.DeleteItemView.as_view(), name="delete-item"),
    path('item-view/<int:pk>/edit', views.ItemEditView.as_view(), name="edit-item"),
    path('comment/<int:pk>/', views.PostComment.as_view(), name='add-comment'),
    path('comment/<int:pk>/delete/', views.DeleteCommentView.as_view(), name='delete-comment'),
    path('comment/<int:pk>/edit/', views.CommentEditView.as_view(), name='edit-comment'),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
]

home/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from django.conf import settings
from django import forms


class User(models.Model):
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)

    def __str__(self):
        return self.username


class UserDetail(models.Model):
    zipcode = models.CharField(max_length=200)
    username = models.CharField(max_length=200)
    firstname = models.CharField(max_length=200)
    lastname = models.CharField(max_length=200)
    phone = models.CharField(max_length=200, validators=[MinLengthValidator(10)])
    email = models.EmailField(max_length=200)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.username


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Item(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True)
    authors = models.CharField(max_length=200)
    year = models.IntegerField(null=True)
    posted_date = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='likes')
    dislikes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='dislikes')

    class Meta:
        ordering = ['-posted_date']

    def __str__(self):
        return self.name


class Comment(models.Model):
    content = models.TextField()
    data_added = models.DateTimeField(auto_now_add=True)
    item = models.ForeignKey(Item, related_name="comments", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-data_added']

    def __str__(self):
        return self.content

home/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.widgets import PasswordInput, TextInput
from django.contrib.auth.hashers import make_password
from django.contrib.auth import get_user_model
from django.utils.translation import gettext as _
from home.models import UserDetail, Item, Comment


class UserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password', 'email')
        error_messages = {
            'username': {
                'unique': _("Podany login jest już zajęty.")
            }
        }
        widgets = {
            'username': TextInput(attrs={'placeholder': 'Nazwa użytkownika'}),
            'password': PasswordInput(attrs={
                'class': 'form-control',
                'placeholder': 'Tajne hasło:'
            }),
            'email': TextInput(attrs={'placeholder': 'Adres e-mail'})
        }

    def save(self, commit=True, *args, **kwargs):
        m = super().save(commit=False)
        m.password = make_password(self.cleaned_data.get('password'))
        m.username = self.cleaned_data.get('username').lower()

        if commit:
            m.save()
        return m


class UserDetailForm(forms.ModelForm):
    class Meta:
        model = UserDetail
        fields = '__all__'


class AddItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'description', 'authors', 'year', 'user', 'category']

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

home/views.py
from random import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.forms import modelformset_factory
from django.http import request, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import DetailView, FormView, UpdateView, DeleteView
from django.views.generic.detail import SingleObjectMixin

from home.forms import UserForm, AddItemForm, AddCommentForm
from home.models import Item, Comment


class HomeView(View):
    def get(self, request):
        items = Item.objects.all().order_by('-likes')
        items_list = list(items)
        ctx = {'item1': items_list[0], 'item2': items_list[1], 'item3': items_list[2]}
        return render(request, "home/home.html", ctx)

    def post(self, request):
        return render(request, 'home/home.html')


def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Registration succesful.')
            return redirect('home:home')
        messages.error(request, 'Unsuccessful registration. Invalid information')
    else:
        form = UserForm()

    return render(request, 'home/signup.html', {'form': form})


def login_user(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("home:home")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="home/login.html", context={"login_form": form})


def logout_user(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect('home:home')


def item(request):
    if request.method == 'POST':
        form = AddItemForm(request.POST)
        # breakpoint()
        if form.is_valid():
            form.save()
            return redirect('home:home')
    else:
        form = AddItemForm()
    return render(request, 'home/add_item.html', {'add_item': form})



def item_view(request):
    items_list = Item.objects.all()
    paginator = Paginator(items_list, 2)
    page = request.GET.get('page')
    items = paginator.get_page(page)
    ctx = {"items": items}
    return render(request, "home/item_view.html", ctx)


class AddLike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        post = Item.objects.get(pk=pk)
        is_dislike = False
        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break
        if is_dislike:
            post.dislikes.remove(request.user)
        is_like = False
        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break
        if not is_like:
            post.likes.add(request.user)

        if is_like:
            post.likes.remove(request.user)

        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)

class AddDislike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        post = Item.objects.get(pk=pk)
        is_like = False
        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break
        if is_like:
            post.likes.remove(request.user)
        is_dislike = False
        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break
        if not is_dislike:
            post.dislikes.add(request.user)

        if is_dislike:
            post.dislikes.remove(request.user)

        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)



class PostDisplay(DetailView):
    model = Item
    template_name = 'home/item_details.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AddCommentForm()
        return context


class ItemEditView(LoginRequiredMixin, UpdateView):
    model = Item
    fields = ['name', 'description', 'authors', 'year', 'user', 'category']
    template_name = 'home/edit_item.html'

    def get_success_url(self):
        messages.success(
            self.request, 'Your post has been changed successfully.')
        return reverse_lazy('home:home')

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

class DeleteItemView(LoginRequiredMixin, DeleteView):
    model = Item
    fields = ["name"]
    template_name = 'home/delete_item.html'

    def get_success_url(self):
        messages.success(
            self.request, 'Your post has been deleted successfully.')
        return reverse_lazy("home:home")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class PostComment(LoginRequiredMixin, SingleObjectMixin, FormView):
    model = Item
    form_class = AddCommentForm
    template_name = 'home/item_details.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)


    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.item = self.object
        comment.user = self.request.user
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        post = self.get_object()
        return reverse('home:item_details', kwargs={'pk': post.pk}) + '#comments'


class CommentUpdateView(LoginRequiredMixin, UpdateView):
    model = Comment
    fields = ["content"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        update = True
        context['update'] = update

        return context

    def get_success_url(self):
        messages.success(
            self.request, 'Your post has been updated successfully.')
        return reverse_lazy("home:item_details")

    def get_queryset(self):
        return self.model.objects.filter(author=self.request.user)


class DeleteCommentView(LoginRequiredMixin, DeleteView):
    model = Comment
    fields = ["content"]
    template_name = 'home/delete_comment.html'

    def get_success_url(self):
        messages.success(
            self.request, 'Your post has been deleted successfully.')
        return reverse_lazy("home:home")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

class CommentEditView(LoginRequiredMixin, UpdateView):
    model = Comment
    fields = ['content']
    template_name = 'home/edit_comment.html'

    def get_success_url(self):
        messages.success(
            self.request, 'Your comment has been changed successfully.')
        return reverse_lazy('home:home')

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

home/templates/home/add_comment.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
Add-comment
{% endblock %}

{% block container %}

    <form action="" method="POST"`>

        {% csrf_token %}

        {{ add_comment | crispy }}

        <button type="submit" class="btn btn-primary">Add</button>

    </form>

{% endblock %}

home/templates/home/add_item.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
Add-item
{% endblock %}

{% block container %}

    <form action="" method="POST"`>

        {% csrf_token %}

        {{ add_item | crispy }}

        <button type="submit" class="btn btn-primary">Add</button>

    </form>

{% endblock %}

home/templates/home/delete_comment.html
{% extends 'base.html' %}

{% block title %}
Delete-comment
{% endblock %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h2 class=" my-5">Delete comment</h2>

      <form action="" method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete it?</p>
        <button type="submit" class="btn btn-danger">Delete
        </button>

      </form>
    </div>
  </div>
</div>


{% endblock %}

home/templates/home/delete_item.html
{% extends 'base.html' %}

{% block title %}
Delete-comment
{% endblock %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h2 class=" my-5">Delete item</h2>

      <form action="" method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete it?</p>
        <button type="submit" class="btn btn-danger">Delete
        </button>

      </form>
    </div>
  </div>
</div>


{% endblock %}

home/templates/home/edit_comment.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
Edit-comment
{% endblock %}

{% block container %}

    <form action="" method="POST">

        {% csrf_token %}

        {{ form | crispy }}

        <button type="submit" class="btn btn-primary">Save</button>

    </form>



{% endblock %}

home/templates/home/edit_item.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
Edit-Item
{% endblock %}

{% block container %}

    <form action="" method="POST">

        {% csrf_token %}

        {{ form | crispy }}

        <button type="submit" class="btn btn-primary">Save</button>

    </form>



{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block scripts %}
    {{ block.super }}
{% endblock %}

{% block styles %}
    {{ block.super }}
{% endblock %}

{% block container %}

{% endblock %}


{% block content %}
{% include 'partial/_carousel.html' %}

<p>
  <button class="badge bg-info text-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample">
    More Books...
  </button>
</p>
<div style="">
  <div class="collapse collapse-horizontal" id="collapseWidthExample">
    <div class="card card-body" style="width: 300px;">
      If you want to read more, go to books tab in menu.
    </div>
      <a href="{% url 'home:item_view' %}" class="btn btn-primary">Go to Books</a>
  </div>
</div>
{% endblock %}

home/templates/home/item_details.html
{% extends 'base.html' %}

{% block title %}
Item-details
{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="card col-lg-6 offset-lg-3 mb-3">
      <div class="card-body">
          <h2 class="card-title my-3"> </h2>
        </a>
        <div class="text-muted mb-3">
          <div><h1>{{ post.name }}</h1>
              {% if image %}
              <img src="{{ image.url }}" class="img-thumbnail" alt="book_image">
              {% endif %}
            <span>created: {{ post.posted_date|date:"N j Y" }} |</span>
            <span>updated: {{ post.updated_on|timesince }} ago |</span>
            <span>author: {{ post.user }}</span>
          </div>
            <p class="card-text">{{ post.description}}</p>
        </div>

          <div class="d-flex flex-row">
                <form method="POST" action="{% url 'home:like' post.pk %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button style="background-color: transparent; border: none; box-shadow: none;" type="submit"><i class="far fa-thumbs-up"></i> <span>{{ post.likes.all.count }}</span> like</button>
                </form>
                <form method="POST" action="{% url 'home:dislike' post.pk %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button style="background-color: transparent; border: none; box-shadow: none;" type="submit"><i class="far fa-thumbs-down"></i> <span>{{ post.dislikes.all.count }}</span> dislike</button>
                </form>
            </div>

        <h2>Comments...</h2>
        {% for comment in post.comments.all %}
        <b>{{ comment.user }}</b> said <b>{{ comment.data_added|timesince }} ago</b>
        <p>{{ comment.content }}</p>
        {% if comment.user == request.user %}
        <div class="mt-4 mx-3">
          <a class="btn btn-danger" href="{% url 'home:delete-comment' pk=comment.id %}">Delete</a>
          <a class="btn btn-danger" href="{% url 'home:edit-comment' pk=comment.id %}">Edit</a>
        </div>
        {% endif %}
        {% empty %}
        <p>Feel free to leave the first comment!</p>
        {% endfor %}
        <hr>
        <h3>Add a comment</h3>
        <form action="{% url 'home:add-comment' object.pk %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" >Submit</button>
        </form>
  </div>
</div>

 {% if post.user == request.user %}
  <div class="mt-4 mx-3">
      <a class="btn btn-danger" href="{% url 'home:delete-item' post.id %}">Delete</a>
      <a class="btn btn-danger" href="{% url 'home:edit-item' post.id %}">Edit</a>
  </div>
  {% endif %}

{% endblock %}

home/templates/home/item_view.html
{% extends 'base.html' %}
{% block title %}
Item-view
{% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="row">
      {% for entry in items %}
      <div class="card col-lg-6 offset-lg-3 mb-3">
        {% if entry.image %}
        <img class="card-img-top mt-3" style="width: 15rem" src="{{ entry.image.url }}" alt="{{ entry.name }}">
        {% endif %}
        <div class="card-body">
          <a href="{% url 'home:item_view' %}">
            <h2 class="card-title my-3">{{ entry.name }} </h2>
          </a>
        <div class="text-muted mb-3">
            <p><strong>{{ entry.category }}</strong></p>
            <span>created: {{ entry.posted_date|date:"N j Y" }} |</span>
            <span>updated: {{ entry.updated_on|timesince }} ago |</span>
            <span>author: {{ entry.user }}</span>
        <p class="card-text">{{ entry.description|truncatewords:20 }}</p>
        <a class='btn btn-primary' href="{% url 'home:item_details' entry.id %}">Read more ...</a>
      </div>
    </div>
  </div>

{% endfor %}
  <!-- Pagination -->
  <div class="row">
    <nav class="col-lg-6 offset-lg-3 mt-4 d-flex justify-content-center">
      <ul class="pagination">

        {% if items.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ items.previous_page_number }}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Previous</a>
        </li>
        {% endif %}

        {% for i in items.paginator.page_range %}
        <li class=" page-item {% if page_obj.number == i %}active{% endif %}">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
        {% endfor %}

        {% if items.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ items.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Next</a>
        </li>
        {% endif %}

      </ul>
    </nav>
  </div>
  <!-- /Pagination -->

</div>


{% endblock %}

home/templates/home/login.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
Login
{% endblock %}

{% block container %}

    <form action="{% url 'home:login' %}" method="POST"`>

        {% csrf_token %}

        {{ login_form | crispy }}

        <button type="submit" class="btn btn-primary">Login</button>

    </form>

    <p class="text-center">Don't have an account? <a href="{% url 'home:signup' %}">Create account</a>.</p>


{% endblock %}

home/templates/home/signup.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
Signup
{% endblock %}

{% block container %}

    <form action="{% url 'home:signup' %}" method="POST"`>

        {% csrf_token %}

        {{ form | crispy }}

        <button type="submit" class="btn btn-primary">Signup</button>

    </form>
    <p class="text-center">If you already have an account? <a href="{% url 'home:login' %}">Login</a>.</p>


{% endblock %}