config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('signup/', views.signup, name="signup"),
    path('item/', views.item, name="add_item"),
    path('item-view/', views.item_view, name="item_view"),
    path('item-view/<int:pk>/', views.PostDisplay.as_view(), name="item_details"),
    path('item-view/<int:pk>/like', views.AddLike.as_view(), name="like"),
    path('item-view/<int:pk>/dislike', views.AddDislike.as_view(), name="dislike"),
    path('item-view/<int:pk>/delete', views.DeleteItemView.as_view(), name="delete-item"),
    path('item-view/<int:pk>/edit', views.ItemEditView.as_view(), name="edit-item"),
    path('comment/<int:pk>/', views.PostComment.as_view(), name='add-comment'),
    path('comment/<int:pk>/delete/', views.DeleteCommentView.as_view(), name='delete-comment'),
    path('comment/<int:pk>/edit/', views.CommentEditView.as_view(), name='edit-comment'),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
]

templates/partial/_carousel.html
{% load static %}
<div id="carouselExampleCaptions" class="carousel slide" style="width: 42rem" data-bs-ride="carousel" >
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>

  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/gradient.jpg' %}" class="d-block w-100" alt="gradient" >
      <div class="carousel-caption">
        {% if item1.image %}
        <img class="card-img-top mt-3" style="width: 15rem" src="{{ item1.image.url }}" alt="{{ item1.name }}">
        {% endif %}
        <h5>{{ item1.name }}</h5>
        <p>{{ item1.description|truncatewords:20 }}</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/gradient.jpg' %}" class="d-block w-100" alt="gradient">
      <div class="carousel-caption d-none d-md-block">
        {% if item2.image %}
        <img class="card-img-top mt-3" style="width: 15rem" src="{{ item2.image.url }}" alt="{{ item2.name }}">
        {% endif %}
         <h5>{{ item2.name }}</h5>
        <p>{{ item2.description|truncatewords:20 }}</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/gradient.jpg' %}" class="d-block w-100" alt="gradient">
      <div class="carousel-caption d-none d-md-block">
        {% if item3.image %}
        <img class="card-img-top mt-3" style="width: 15rem" src="{{ item3.image.url }}" alt="{{ item3.name }}">
        {% endif %}
         <h5>{{ item3.name }}</h5>
        <p>{{ item3.description|truncatewords:20 }}</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

templates/partial/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home:home' %}">
      <img class="logo" src="{% static 'images/log.svg' %}" alt="Logo">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
        </li>
        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'home:signup' %}">Signup</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'home:login' %}">Login</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'home:add_item' %}">Add Book</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'home:item_view' %}">Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'home:logout' %}">Logout</a>
        </li>
        <li>
          <a class="nav-link" aria-current="page">{{ user }}</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>